@startuml

package view{

    class StringConstant{

    }

    class GraphicConstant{

    }

    class MainObserver{
        + changeCurrentView()
    }


    class LoadView{

    }

    class TextureFactory{

    }
    note bottom: Class that provides images\nused on elements such as ship

    class MainMenu{

    }

    abstract GameView{

    }

    class GameViewIA{

    }

}

class Observer{

}

class JPanel{

}

MainObserver .up.|> Observer
MainObserver --> "1" JPanel: - currentView

MainMenu -up-|> JPanel
LoadView -up-|> JPanel
GameView -up-|> JPanel

GameViewIA --|> GameView

@enduml