@startuml
actor player
player -> GUI: Click on tile to attack
GUI ->  ShipShop: attack(assaillant : int, x: int, y: int, numGrille: int)
ShipShop -> Game: attack(assaillant : int, x: int, y: int, numGrille: int)
Game -> Army: dmg = getDmg(assaillant: int)

Army -> Grid : dmg = getDmg(assaillant: int)

Grid -> Ship : dmg = getDmg()

Game -> Game: army = getArmy(numGrille: int)

Game -> Army: getHit(x: int, y: int, dmg: int)
Army -> Grid: hitShip(x: int, y: int, dmg: int, ship: int)
Grid -> Ship: takeDamage(dmg: int)

ShipShop -> ShipShop: setChanged()
ShipShop -> Observable: notifieObserver()
Observable -> GUI: update()

@enduml