@startuml
actor player
player -> GUI: Click on tile to attack
GUI ->  ShipShop: attack(assaillant : int, x: int, y: int)
ShipShop -> Game: attack(assaillant : int, x: int, y: int)

Game -> "current: Army": dmg = getDmg(assaillant: int)

"current: Army" -> "current: Grid" : dmg = getDmg(assaillant: int)

"current: Grid" -> "assaillant: Ship" : dmg = getDmg()


Game -> "next: Army": getHit(x: int, y: int, dmg: int)
"next: Army" -> "next: Grid": hitShip(x: int, y: int, dmg: int, ship: int)
"next: Grid" -> "victim: Ship": takeDamage(dmg: int)

ShipShop -> ShipShop: setChanged()
ShipShop -> ShipShop: notifieObserver()
ShipShop -> GUI: update()

GUI --> player: Flag on the tile

@enduml