@startuml
title When the player change the tactic

autonumber
actor player

player -> GUI: Select tactic

GUI -> ShipShop: setTactic(Player player, Tactic tactic)

ShipShop -> Game: setTactic(Player player, Tactic tactic)

Game -> Player:  setTactic(Tactic tactic)

@enduml
