@startuml

title When a player move a ship on his grid

autonumber
actor player

player -> GUI: The player wants to move a ship

GUI -> ShipShop: placeShip(move)

ShipShop -> Game: placeShip(move)

Game ->

@enduml