@startuml

title When a player move a cruiser on his grid (for the first time)

autonumber
actor player

player -> GUI: The player wants to move a ship

GUI -> ShipShop: placeShip(move)

ShipShop -> Game: placeShip(move)

Game -> "current: Player": placeShip(move)

"current: Player" -> "current: Grid": placeShip(move)

"current: Grid" -> Ship: placeShip(move)

"current: Grid" --> "current: Player": UUID

"current: Player" --> Game: UUID

Game --> ShipShop: UUID

ShipShop -> ShipShop: setChanged()

ShipShop -> ShipShop: notifyObserver( PLACE )

ShipShop --> GUI: The GUI is updated by the observable

GUI --> player: update the gui on the grid

@enduml