@startuml

title When a player is ending is turn

autonumber
actor player

player -> GUI: Click to end his turn

GUI -> ShipShop: play(attack)

note left
The controller is creating an attack
object which contains every information
about the action of the player (target tile, and
the ship that shoot)
end note

ShipShop -> Game: play(attack)


note left
UUID is an unique ID used
to recognize the ship
end note

Game -> "next: IA": isShip(x, y)

"next: IA" -> "next: Grid": isShip(x, y)

"next: Grid" -> "next: IA": information

"next: IA" -> Game: information

alt information == true

    Game -> "current: Player": canAttack(UUID)

    "current: Player" -> "current: Grid": canAttack(UUID)

    "current: Grid" -> Ship: canAttack()

    Ship --> "current: Grid": information2

    "current: Grid" --> "current: Player": information2

    "current: Player" --> Game: information2

    opt information2 == true

        note left
            checking if the ship can actually
            shoot something (no ammo, has sunk)
        end note

        Game -> "current: Player": getDmg(UUID)

        "current: Player" -> "current: Grid": getDmg(UUID)

        "current: Grid" -> Ship: getDmg()

        Ship --> "current: Grid": dmg

        "current: Grid" --> "current: Player": dmg

        "current: Player" --> Game: dmg

        Game -> "next: IA": hit(x, y, dmg)

        "next: IA" -> "next: Grid": hit(x, y, dmg)

        "next: Grid" -> Ship: hasSunk()

        Ship -> "next: Grid": information3

        opt information3 == false

            "next: Grid" -> Ship: hit(dmg)

        end

        Game -> "current: Player": flagTile(x, y)

        "current: Player" -> "current: Grid": flagTile(x, y)

    end

else information == false

    Game -> "current: Player": crossTile(x, y)

    "current: Player" -> "current: Grid": crossTile(x, y)

end

Game -> Game: isFinished()

note left
    Checking if the game
    is finished
end note

Game -> "current: Player": isDefeated()

"current: Player" -> "current: Grid": isDefeated()

loop for each ship

    "current: Grid" -> Ship: sunk = hasSunk()

    "current: Grid" -> Ship: shoot = canShoot()

end

"current: Grid" --> "current: Player": defeat

"current: Player" --> Game: defeat

note left
    Same thing for the next
    player
end note


opt both players have at least one ammunition and one ship alive

    Game -> Game: next()

    note left
        Changing the current player,
        if it's an IA, it plays
    end note

    Game -> "next: IA": isHuman()

    "next: IA" --> Game: human

    opt human == false

        Game -> "next: IA": getBestMove()

        "next: IA" -> Tactic: applyTactic(next)

        Tactic --> "next: IA": bestMove

        "next: IA" --> Game: bestMove

        Game -> Game: Play(bestMove)

    end

end

Game --> ShipShop: List<Attack>

note left
    Game is giving to ShipShop
    a list of the moves
end note

ShipShop -> ShipShop: setChanged()

ShipShop -> ShipShop: updateObserver( PLAY )

ShipShop --> GUI: the gui is updated by the observable

GUI --> player: Flag on the tile

@enduml