@startuml
title When a new game is requested

autonumber
actor player

player -> GUI: Click on play

GUI -> GUI: era = selectEra()
player -> GUI: Click on Era

GUI -> GUI: tc = selectTactic()
player -> GUI: Click on tactic

GUI -> GUI: fp = selectFirstPlayer()
player -> GUI: Click on first player


GUI -> ShipShop: createGame(era, tc, true)

note left
In this case, the human plays
first.
end note

ShipShop -> GameFactory: game = getPvEGame(era)

GameFactory -> Game:  game = game(Era era, Player p1, Player p2)
ShipShop -> Game: setTactic(int p2, Tactic tc)
Game -> Player: setTactic(Tactic tc)

Game -> Era: getFleetFactory()

@enduml
